---
# Colecciones de Ansible necesarias
# Instalar con: ansible-galaxy collection install -r requirements.yml

collections:
  - name: containers.podman
    version: ">=1.10.0"
  - name: community.general
    version: ">=6.0.0"
